
spring:
    # In dev we use hibernate DDL and not flyway
    flyway:
        enabled: false
    jpa:
        properties:
            hibernate:
                #format_sql: false
                hbm2ddl:
                    auto: create-drop
        show-sql: false
